In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [5]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
independent = dataset [['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent = dataset [['charges']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split (independent,dependent,test_size=0.30,random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor

param_grid = { 'criterion': ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
              'splitter': ['best','random'] }

grid=GridSearchCV(DecisionTreeRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [16]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'splitter': 'random'}:

In [17]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.009435,0.000703,0.003526,0.000327,squared_error,best,"{'criterion': 'squared_error', 'splitter': 'be...",0.743817,0.570859,0.760524,0.643223,0.641046,0.671894,0.070725,2
1,0.030675,0.030331,0.003215,0.000269,squared_error,random,"{'criterion': 'squared_error', 'splitter': 'ra...",0.616576,0.514330,0.610578,0.642811,0.627090,0.602277,0.045314,8
2,0.009171,0.001577,0.003554,0.000849,friedman_mse,best,"{'criterion': 'friedman_mse', 'splitter': 'best'}",0.736077,0.539607,0.764719,0.637948,0.659679,0.667606,0.079304,3
3,0.007009,0.000882,0.004710,0.001767,friedman_mse,random,"{'criterion': 'friedman_mse', 'splitter': 'ran...",0.693374,0.709002,0.691380,0.644478,0.674798,0.682607,0.021929,1
4,0.044808,0.011361,0.003291,0.001123,absolute_error,best,"{'criterion': 'absolute_error', 'splitter': 'b...",0.749234,0.623792,0.620771,0.523676,0.666851,0.636865,0.073168,6
5,0.024001,0.003948,0.002821,0.000269,absolute_error,random,"{'criterion': 'absolute_error', 'splitter': 'r...",0.644826,0.621772,0.748379,0.651567,0.609323,0.655173,0.049041,5
6,0.009498,0.001059,0.003976,0.000970,poisson,best,"{'criterion': 'poisson', 'splitter': 'best'}",0.707878,0.571969,0.724174,0.553113,0.605543,0.632536,0.070397,7
7,0.007533,0.001587,0.004225,0.000899,poisson,random,"{'criterion': 'poisson', 'splitter': 'random'}",0.688449,0.706445,0.629786,0.660902,0.643140,0.665744,0.028282,4

In [18]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 30
BMI: 45
Children: 1
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [19]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[63770.42801]