In [1]:
import pandas as pd

In [2]:
dataset = pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset = pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
independent = dataset [['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
dependent = dataset [['charges']]

In [6]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [7]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split (independent,dependent,test_size=0.30,random_state=0)

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
X_train

array([[-1.5330973 , -0.40713453, -0.89833872, -0.97676557, -0.50466988],
       [-0.03364163,  0.32855417, -0.89833872, -0.97676557, -0.50466988],
       [ 0.89459283,  2.56690911,  3.25603402, -0.97676557, -0.50466988],
       ...,
       [ 0.03776102, -0.91016269, -0.89833872,  1.02378711, -0.50466988],
       [-1.46169465,  0.76659782, -0.89833872,  1.02378711, -0.50466988],
       [-0.46205754, -1.96596021, -0.06746417, -0.97676557, -0.50466988]])

In [11]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = { 'criterion': ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
              'n_estimators': [10,100,1000,2000,3000] } 

grid=GridSearchCV(RandomForestRegressor(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(X_train,y_train)

Fitting 5 folds for each of 20 candidates, totalling 100 fits

C:\Users\kavvi\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'friedman_mse',
                                       'absolute_error', 'poisson'],
                         'n_estimators': [10, 100, 1000, 2000, 3000]},
             verbose=3)

In [12]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'poisson', 'n_estimators': 1000}:

In [13]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.070283,0.003638,0.006068,0.000706,squared_error,10,"{'criterion': 'squared_error', 'n_estimators':...",0.847640,0.730322,0.810924,0.806794,0.764693,0.792075,0.040553,17
1,0.509031,0.007264,0.026349,0.001232,squared_error,100,"{'criterion': 'squared_error', 'n_estimators':...",0.862617,0.767528,0.812357,0.810369,0.770384,0.804651,0.034654,4
2,6.099407,0.094707,0.296526,0.011591,squared_error,1000,"{'criterion': 'squared_error', 'n_estimators':...",0.865552,0.767730,0.816634,0.801739,0.770535,0.804438,0.035743,5
3,13.018993,0.389897,0.567752,0.030976,squared_error,2000,"{'criterion': 'squared_error', 'n_estimators':...",0.864927,0.767098,0.815517,0.802733,0.769277,0.803911,0.035816,10
4,20.848119,0.286911,0.950630,0.103129,squared_error,3000,"{'criterion': 'squared_error', 'n_estimators':...",0.865277,0.766989,0.816351,0.803398,0.769198,0.804243,0.036024,8
5,0.084193,0.015158,0.008410,0.002398,friedman_mse,10,"{'criterion': 'friedman_mse', 'n_estimators': 10}",0.835717,0.728021,0.816662,0.790725,0.766449,0.787515,0.037859,18
6,0.712212,0.105516,0.030278,0.001286,friedman_mse,100,"{'criterion': 'friedman_mse', 'n_estimators': ...",0.867443,0.767070,0.817252,0.797719,0.772482,0.804393,0.036322,6
7,6.608442,0.280279,0.275562,0.014249,friedman_mse,1000,"{'criterion': 'friedman_mse', 'n_estimators': ...",0.866790,0.766657,0.816961,0.801704,0.769189,0.804260,0.036665,7
8,12.636965,0.078685,0.559947,0.013977,friedman_mse,2000,"{'criterion': 'friedman_mse', 'n_estimators': ...",0.865388,0.767238,0.816112,0.801537,0.768919,0.803839,0.036064,11
9,19.216107,0.180713,0.957030,0.186048,friedman_mse,3000,"{'criterion': 'friedman_mse', 'n_estimators': ...",0.865027,0.766990,0.817296,0.802265,0.769050,0.804126,0.036042,9
10,0.279245,0.108366,0.008964,0.001832,absolute_error,10,"{'criterion': 'absolute_error', 'n_estimators'...",0.832669,0.785557,0.784887,0.759869,0.747594,0.782115,0.029195,20
11,2.053838,0.061675,0.030404,0.002409,absolute_error,100,"{'criterion': 'absolute_error', 'n_estimators'...",0.849191,0.773531,0.793991,0.796856,0.762732,0.795260,0.029809,16
12,20.205649,0.145296,0.257638,0.006177,absolute_error,1000,"{'criterion': 'absolute_error', 'n_estimators'...",0.849551,0.776638,0.799832,0.799538,0.765287,0.798169,0.028947,14
13,42.010316,0.641615,0.561910,0.051185,absolute_error,2000,"{'criterion': 'absolute_error', 'n_estimators'...",0.849801,0.780446,0.798635,0.798104,0.764256,0.798248,0.028741,13
14,60.121161,0.212351,0.791227,0.023872,absolute_error,3000,"{'criterion': 'absolute_error', 'n_estimators'...",0.848419,0.778188,0.799527,0.798559,0.764839,0.797906,0.028414,15
15,0.072521,0.001486,0.005784,0.000158,poisson,10,"{'criterion': 'poisson', 'n_estimators': 10}",0.838818,0.744459,0.792531,0.784835,0.772492,0.786627,0.030789,19
16,0.684406,0.024708,0.029637,0.003884,poisson,100,"{'criterion': 'poisson', 'n_estimators': 100}",0.862081,0.768682,0.810574,0.801953,0.771822,0.803022,0.033761,12
17,6.748350,0.043372,0.266631,0.007112,poisson,1000,"{'criterion': 'poisson', 'n_estimators': 1000}",0.866651,0.771083,0.815229,0.804912,0.770172,0.805609,0.035403,1
18,13.745018,0.139638,0.545483,0.018695,poisson,2000,"{'criterion': 'poisson', 'n_estimators': 2000}",0.867202,0.767403,0.817486,0.803700,0.769603,0.805079,0.036587,3
19,20.577707,0.748488,0.823188,0.149110,poisson,3000,"{'criterion': 'poisson', 'n_estimators': 3000}",0.867263,0.769504,0.815265,0.803925,0.769689,0.805129,0.036028,2

In [14]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 25
BMI: 45
Children: 1
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [15]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])

print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[56224.99813845]